crptest

diff --git a/dcrpt b/dcrpt
--- a/dcrpt
+++ b/dcrpt
@@ -3,20 +3,20 @@
 # using corresponding keys in the specified directory 'keysname'
 # into corresponding original files in local directory 'dirname_org' 
 
-PNAME=${0##*/}
+PROGN=${0##*/}
 case $# in
 	0|1)
-		printf "$PNAME quitting, needs keysdir encrypteddir\n" 
+		printf "$PROGN quitting, needs keysdir encrypteddir\n" 
 		exit 2;; 
 	2)
       if ! [ -d "$1" ]; then
-		printf "$PNAME quitting, keys directory $1 not found\n"
+		printf "$PROGN quitting, keys directory $1 not found\n"
 		exit 2; fi
 		if ! [ -d "$2" ]; then
-		printf "$PNAME quitting, encrypted directory $2 not found\n"
+		printf "$PROGN quitting, encrypted directory $2 not found\n"
 		exit 2; fi;;		
 	*) 
-		printf "$PNAME quitting, needs keysdir encrypteddir\n" 
+		printf "$PROGN quitting, needs keysdir encrypteddir\n" 
 		exit 2;;
 esac
 
@@ -27,9 +27,10 @@ OUTDIR=${2##*/} # just the last directory name, path is stripped off
 # if the indir ending is standard _crp, then remove it from outdir
 if [ "${OUTDIR##*_}" == 'crp' ]; then OUTDIR=${OUTDIR%_*}; fi
 OUTDIR="$OUTDIR"_org # in any case append _org, i.e. original files reconstructed
+
 # make output directory for all decrypted files
 if [ -d "$OUTDIR" ]; then 
-	printf "$PNAME quitting, '$OUTDIR' already exists here!\n"; exit 2
+	printf "$PROGN quitting, '$OUTDIR' already exists here!\n"; exit 2
 else mkdir $OUTDIR; fi
 
 # decompress all files in INDIR
@@ -56,8 +57,8 @@ for INFILE in $INDIR/*; do
 		symcrypt $KEYFILE.hex.lz $INFILE | lzma -d -c | xxd -p > $OUTFILE
 		continue
 	fi
-	printf "$PNAME failed to find key for encrypted file $FILEND\n"
+	printf "$PROGN failed to find key for encrypted file $FILEND\n"
 	let COUNT-=1
 	let FAILED+=1
 done
-printf "$PNAME: decrypted $COUNT files into $OUTDIR, $FAILED failures\n"
+printf "$PROGN: decrypted $COUNT files into $OUTDIR, $FAILED failures\n"
diff --git a/ncrpt b/ncrpt
--- a/ncrpt
+++ b/ncrpt
@@ -3,18 +3,18 @@
 # into corresponding encrypted binary files in local directory 'dirname-ecr' 
 # with corresponding key files in 'dirname-key'
 
-PNAME=${0##*/}
+PROGN=${0##*/}
 
 case $# in
 	0)
-		printf "$PNAME quitting, requires one input path argument\n"
+		printf "$PROGN quitting, requires one input path argument\n"
 		exit 2;; 
 	1)
       	if ! [ -d "$1" ]; then
-		printf "$PNAME quitting, directory $1 not found\n"
+		printf "$PROGN quitting, directory $1 not found\n"
 		exit 2; fi;;
 	*) 
-		printf "$PNAME quitting, too many arguments, needs just one path\n" 
+		printf "$PROGN quitting, too many arguments, needs just one path\n" 
 		exit 2;;
 esac
 
@@ -22,14 +22,12 @@ DIREND=${1##*/} # just the directory name, preceding path stripped off
 OUTDIR="$DIREND"_crp
 KEYDIR="$DIREND"_key
 
-# make output directory for all encrypted files
-if [ -d "$OUTDIR" ]; then 
-	printf "$PNAME quitting, '$OUTDIR' already exists here!\n"; exit 2
-else mkdir $OUTDIR; fi
-# make keys directory
+# prepare output directories
 if [ -d "$KEYDIR" ]; then
-	printf "$PNAME quitting, '$KEYDIR' already exists here!\n";	exit 2
-else mkdir $KEYDIR; fi
+	printf "$PROGN quitting, '$KEYDIR' already exists here!\n";	exit 2; fi
+if [ -d "$OUTDIR" ]; then 
+	printf "$PROGN quitting, '$OUTDIR' already exists here!\n"; exit 2; fi
+mkdir $KEYDIR $OUTDIR
 
 # compress all files from the given input path/directory in $1
 for FILE in $1/*; do
@@ -62,4 +60,4 @@ for FILE in $1/*; do
 	symcrypt $KEYFILE $BINFILE $OUTFILE
 done
 rm hexfile.tmp binfile.tmp lzfile.tmp > /dev/null #tidy up
-printf "$PNAME: encrypted $COUNT files into $OUTDIR, keys are in $KEYDIR\n"
+printf "$PROGN: encrypted $COUNT files into $OUTDIR, keys are in $KEYDIR\n"
