% reporting

diff --git a/decrypt b/decrypt
--- a/decrypt
+++ b/decrypt
@@ -4,15 +4,13 @@
 # writes restored files with the same names into writeable directory 'outdir' 
 
 PROGN=${0##*/}
-BACKSZ=10000 # size of files to be encrypted in the subshells
 
 # processfile will decompress and decrypt one file
-# it expects four arguments: ITEM INDIR KEYDIR OUTDIR
+# it expects four arguments: ITEM INDIR KEYFILE OUTDIR
 function processfile {
 
 	local INFILE=$1 
-	local KEYFILE=$2
-	local OUTFILE=$3 
+	local OUTFILE=$2
 
    	if [ -f $KEYFILE ]; then # found key with no extra extensions
 		symcrypt $KEYFILE $INFILE $OUTFILE # just decrypt the infile and save it
@@ -56,44 +54,28 @@ function processfile {
 # function to process a whole directory
 # takes three arguments: INDIR KEYDIR OUTDIR
 function processdir {
-	[ -n "$3" ] || { 
-		printf "$PROGN quitting, outdir is not set!\n" >&2
-		exit 2
-	}
-	[ -e "$3" ] && { 
-		printf "$PROGN quitting, outdir $3 already exists!\n" >&2
-		exit 2
-	}
-	# create the ouput directory
-	mkdir $3
-	[ "$?" -ne 0 ] && {
-		printf "$PROGN quitting, failed to create output directory $3!\n" >&2
-		exit 2
-	}
 
-	# sort files in INDIR by size
-	# stripping the path path prior to using ls was done thus: FILEND=${INFILE##*/} 
-	local ITEMS=$(ls -SAL $1)
-	# prepare to fire off subshells
-	local BJ=\&
-
+	# create the ouput directory 
+	mkdir $2 || {
+		printf "$PROGN processdir: failed to create output directory '$2'!\n" >&2
+		exit 2
+	}
+	local ITEMS=$(ls -AL $1)
 	# iterate through the listing
 	for ITEM in $ITEMS; do
 		local IND=$1/$ITEM
    		if [ -d "$IND" ]; then  # recursively process existing subdirectory?
 			if [ -n "$RECURSE" ]; then  # just push ITEM onto paths, no changing of directories
-				processdir $IND $2/$ITEM $3/$ITEM &
+				processdir $IND $2/$ITEM &
 			fi
 			continue # either processed or ignored this subdir now
 		fi
    		[ -f "$IND" ] || continue # only process genuine file now
- 		# turn off subshells when file size falls below BACKSZ
-   		[ -z "$BJ" ] || [ $( stat -c%s $IND ) -ge $BACKSZ ] || BJ='' 
-   		processfile $IND $2/$ITEM $3/$ITEM $BJ
+   		processfile $IND $2/$ITEM 
 	done
 } # end of processdir
 
-function usage { printf "Usage: $PROGN [-h][-q][-r][-v] indir keydir outdir\n" >&2; }
+function usage { printf "Usage: $PROGN [-h][-q][-r][-v] indir keyfile outdir\n" >&2; }
 
 # Main starts here
 # get options, including long options, extracted as arg to the last option '-'
@@ -122,14 +104,28 @@ shift $((OPTIND-1)) # remove already parsed options and args from $@ list
 
 # Globally validate the input directory
 [ -d "$1" ] || { 
-	printf "$PROGN quitting, input directory $1 not found\n" >&2
+	printf "$PROGN quitting, input directory '$1' not found\n" >&2
 	exit 2
 }
-# Globally validate the key directory
-[ -d "$2" ] || { 
-	printf "$PROGN quitting, key directory $2 not found\n" >&2
+# Globally validate and set the key file
+[ -f "$2" ] || { 
+	printf "$PROGN quitting, key file '$2' not found\n" >&2
 	exit 2
 }
+KEYFILE=$2
+
+# Globally validate the output directory
+[ -n "$3" ] || { 
+	printf "$PROGN quitting, outdir not specified!\n" >&2
+	exit 2
+}
+
+[ -e "$3" ] && { 
+	printf "$PROGN quitting, output directory '$3' already exists!\n" >&2
+	exit 2
+}
+
+
 # Warn about missing decompressors
 if [ -z $( which zstd ) ]; then 
 	printf "$PROGN warning, zstd compressor is not installed, will not decompress .zst files\n" >&2
@@ -145,7 +141,7 @@ if [ -z $( which hexify ) ]; then
 fi
 
 printf "$PROGN: decrypting and decompressing, using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
-processdir $1 $2 $3
+processdir $1 $3
 wait # for all sub proccesses to finish
 
 # optional final report
diff --git a/encrypt b/encrypt
--- a/encrypt
+++ b/encrypt
@@ -1,12 +1,11 @@
 #!/bin/bash
 # encrypts all files in the specified directory 'indir' 
-# writes key files into directory 'keydir', extensions indicating compression methods 
-# writes encrypted binary files with the same names into directory 'outdir' 
+# writes keys into file 'key' 
+# writes encrypted binary files with the same names into directory 'outdir'
 
 PROGN=${0##*/}
 COMPRESSOR=lzma	# the default compression program
-EXT=lz				# and the extension that goes with it
-BACKSZ=10000 # size of files to be encrypted in the subshells
+EXT=lz			# and the extension that goes with it
 
 # function to compress and encrypt one file
 # takes four arguments: ITEM INDIR KEYDIR OUTDIR
@@ -15,8 +14,7 @@ BACKSZ=10000 # size of files to be encrypted in the subshells
 function processfile {
 
 	local INFILE=$1 
-	local KEYFILE=$2
-	local OUTFILE=$3
+	local OUTFILE=$2
 	local EX="${1##*.}" # this file's extension
 	EX=${EX,,} # convert to lower case for ease of detecting either
 
@@ -25,84 +23,85 @@ function processfile {
 	[ "$EX" = 'lz' ] || [ "$EX" = 'zst' ] || [ "$EX" = 'gz' ] || [ "$EX" = 'bz2' ] || {
 
     	[ $HEXTEST ] && {
-   			hexcheck $INFILE $OUTFILE.tmp000 2>/dev/null # ignore failure messages
+   			hexcheck $INFILE $OUTFILE.hex 2>/dev/null # ignore failure messages
    			if [ "$?" -eq 0 ]; then	# status of hexcheck when INFILE is entirely hexadecimal
-				INFILE="$OUTFILE".tmp000 # now this becomes the binary file to further compress
-				KEYFILE="$KEYFILE".hex # append .hex extension for hexadecimal origin
-   			fi
+				OUTFILE=$OUTFILE.hex
+				INFILE="$OUTFILE"
+   			else rm $OUTFILE.hex
+			fi
 		}
 
-		[ $B64TEST ] && [ "$INFILE" = "$1" ] && { #  still the original input file?
-   			base64 -d -w 0 $INFILE > $OUTFILE.tmp000 2>/dev/null # turns base64 into binary, saving 25%
+		[ $B64TEST ] && [ "$OUTFILE" = "$2" ] && { #  not already hexed
+   			base64 -d -w 0 $INFILE > $OUTFILE.b64 2>/dev/null # turns base64 into binary, saving 25%
    			if [ "$?" -eq 0 ]; then	# status of base64 when INFILE was entirely in base64
-				INFILE="$OUTFILE".tmp000 # now this becomes the binary file to further compress
-				KEYFILE="$KEYFILE".b64 # append .b64 extension for base64 origin
+				OUTFILE=$OUTFILE.b64
+				INFILE="$OUTFILE"
+			else rm $OUTFILE.b64
    			fi 
 		}
 	
-		# regardless whether hexcheck or base64 tests succeeded or not, test general compression	
-		$COMPRESSOR $FLAGS $INFILE > $OUTFILE.tmp001 
-		local CMPS=$( stat -c%s $OUTFILE.tmp001 ) # the size after compression
+		# regardless whether hexcheck or base64 tests succeeded or not, apply general compression test	
+		$COMPRESSOR $FLAGS $INFILE > $OUTFILE.$EXT 
+		local CMPS=$( stat -c%s $OUTFILE.$EXT ) # the size after compression
 		local ORGS=$( stat -c%s $INFILE )  # and before compression
 		# use compressed version only if it is actually smaller
-		if [ "$CMPS" -lt "$ORGS" ]; then 
-			KEYFILE="$KEYFILE".$EXT # append compression extension to the keyfile to be generated
-			INFILE="$OUTFILE".tmp001  # assign the compressed file name, else stay with previous
+		if [ "$CMPS" -lt "$ORGS" ]; then
+			# clean up outfile if it exists
+			if [ -e "$OUTFILE" ]; then rm $OUTFILE; fi 
+			OUTFILE=$OUTFILE.$EXT  # assign the better compressed file name
+			INFILE=$OUTFILE # make the final compressed file to be the infile
+		else # clean up and stay with the previous infile
+			rm $OUTFILE.$EXT	
 		fi
 	}
-	# generate and write out the key of the same size as the infile
-	keygen $INFILE > $KEYFILE
-	# encrypt with it and write to OUTFILE 
-	symcrypt $INFILE $KEYFILE $OUTFILE 
-	rm $OUTFILE.tmp000 $OUTFILE.tmp001 2> /dev/null  #tidy up if needed
-}
+	# generate the key of the same size as the infile
+	keygen $INFILE > $OUTFILE.key
+	# encrypt with it and write to final OUTFILE 
+	if [ "$INFILE" = "$OUTFILE" ]; then
+		symcrypt $OUTFILE.key $INFILE $OUTFILE.tmp
+		mv $OUTFILE.tmp $OUTFILE
+	else
+		symcrypt $OUTFILE.key $INFILE $OUTFILE
+	fi
+	# append the key to the global linear keyfile
+	cat $OUTFILE.key >> "$KEYFILE"
+	rm $OUTFILE.key # and remove it
+} # end of processfile
 
 # function to process a whole directory
 # takes three arguments: INDIR KEYDIR OUTDIR
 function processdir {
 
 	[ -z "$2" ] && { 
-		printf "$PROGN processdir: keydir not given!\n" >&2
-		exit 2
-	}
-	[ -e "$2" ] && { 
-		printf "$PROGN processdir: keydir $2 already exists!\n" >&2
-		exit 2
-	}
-	[ -z "$3" ] && { 
 		printf "$PROGN processdir: outdir not given!\n" >&2
 		exit 2
 	}
-	[ -e "$3" ] && { 
-		printf "$PROGN processdir: outdir $3 already exists!\n" >&2
+	[ -e "$2" ] && { 
+		printf "$PROGN processdir: outdir '$2' already exists!\n" >&2
 		exit 2
 	}
 
-	# create the ouput directories
-	mkdir $2 $3 || {
-		printf "$PROGN quitting, failed to create output directories '$2' '$3'!\n" >&2
+	# create the ouput directory
+	mkdir $2 
+	[ "$?" -ne 0 ] && {
+		printf "$PROGN quitting, failed to create output directory '$2'!\n" >&2
 		exit 2
 	}
 
-	# sort files in INDIR by size
-	# stripping the path path prior to using ls was done thus: FILEND=${INFILE##*/} 
-	local ITEMS=$(ls -AL $1)		#$(ls -SAL $1)
-	# prepare to fire off subshells
-	# local BJ=\&
+	# list indir contents in standard order
+	local ITEMS=$(ls -AL $1)
 
 	# iterate through the listing
 	for ITEM in $ITEMS; do
 		local IND=$1/$ITEM # append $ITEM to $INDIR path
    		if [ -d "$IND" ]; then  # recursively process existing subdirectory?
 			if [ -n "$RECURSE" ]; then  # just push ITEM onto paths, no changing of directories
-				processdir $IND $2/$ITEM $3/$ITEM &
+				processdir $IND $2/$ITEM &
 			fi
 			continue # either processed or ignored this subdir now
 		fi
    		[ -f "$IND" ] || continue # only process genuine file now
- 		# turn off subshells when file size falls below BACKSZ
-   		# [ -z "$BJ" ] || [ $( stat -c%s $IND ) -ge $BACKSZ ] || BJ='' 
-   		processfile $IND $2/$ITEM $3/$ITEM & #$BJ 
+   		processfile $IND $2/$ITEM & 
 	done
 } # end of processdir
 
@@ -148,17 +147,15 @@ function updatedir {
 			fi
 			continue # not recursing, ignore this subdir 
 		fi
-   		[ -f "$ID" ] || continue # only process genuine files now
- 		# turn off subshells when file size falls below BACKSZ
-   		# [ -z "$BJ" ] || [ $( stat -c%s $ID ) -ge $BACKSZ ] || BJ='' 
+   		[ -f "$ID" ] || continue # only process genuine files now 
 		[ -e "$OD" ] || { # here $OD file does not exist
 			printf "   a: $ID\n" # so add it
-			processfile $ID $2/$ITEM $OD & #$BJ 
+			processfile $ID $OD &  
 			continue
 		}
 		if [ "$ID" -nt "$OD" ]; then  # here the input file is newer 
 			printf "   u: $ID\n" # so update it
-   			processfile $ID $2/$ITEM $OD & #$BJ 
+   			processfile $ID $OD &  
 		fi # else just skip it
 	done
 } # end of updatedir
@@ -254,13 +251,33 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 	exit 2
 }
 
+# Globally validate the -c option and keyfile
+if [ -z "$UPDATE" ]; then
+	[ -z "$CLEAN" ] || { 
+		printf "$PROGN create failed: option -c only makes sense with -u\n" >&2
+		exit 2
+	}
+	[ -e "$2" ] && {
+		printf "$PROGN create failed: keyfile '$2' already exists\n" >&2
+		exit 2
+	}
+else
+	[ -f "$2" ] || {
+		printf "$PROGN update failed: keyfile '$2' not found\n" >&2
+		exit 2
+	}
+fi
+# Set verified global key file
+KEYFILE=$2
+
 # Globally validate the compressor. It has been set either to lzma or zstd
 [ -z $( which "$COMPRESSOR" ) ] && { 
 	printf "$PROGN quitting, compressor utility $COMPRESSOR not found\n" >&2
 	exit 2
 }
 
-FLAGS='-c -z -q' # the default lags to the compressor
+# Global options for the compressor
+FLAGS='-c -z -q' 
 if [ $VERBOSE ]; then 
 	if [ "$COMPRESSOR" = 'lzma' ]; then FLAGS='-c -z -v';	else FLAGS='-c'; fi
 fi
@@ -270,7 +287,7 @@ if [ $UPDATE ]; then
 	updatedir $1 $2 $3
 else
 	printf "$PROGN: compressing and encrypting $1, using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
-	processdir $1 $2 $3
+	processdir $1 $3
 fi
 wait # for all sub proccesses to finish
 if [ $CLEAN ]; then 
@@ -280,12 +297,14 @@ fi
 wait # for all sub proccesses to finish
 
 # optional final report
-if ! [ $QUIET ]; then
-	SIZES=( $( du -bs $3 $1 ) ) # array of size,dir,size,dir
-	let "SIZES[0]-=4096" 
-	let "SIZES[2]-=4096"	
+if [ ! $QUIET ]; then
+	SIZES=( $( du -bs $3 $1 ) ) # array of size,dir,size,
+	let "SIZES[0]-=4096" # subtract the size of the top directory files
+	let "SIZES[2]-=4096" # as they are not actual data
 	printf "$PROGN: ${SIZES[3]} ${SIZES[2]} => ${SIZES[1]} ${SIZES[0]} "
-	if [ ${SIZES[0]} = ${SIZES[2]} ]; then printf "(100 %%)\n"; else
+	if [ ${SIZES[0]} = ${SIZES[2]} ]; then 
+		printf "(100 %%)\n"
+	else
 		CR=$(( (5+100000*${SIZES[0]}/${SIZES[2]})/10 )) # calculate percentage rounded to two d.p.	
 		printf "(${CR: 0:2}.${CR: 2:4} %%)\n" # compression ratio printed as xx.xx%
 	fi 
