supertest etc

diff --git a/dirtest b/dirtest
--- a/dirtest
+++ b/dirtest
@@ -3,29 +3,31 @@
 # ecrypt encrypts all files in the given directory
 # dcrypt decrypts back all the encrypted files
 
+PROGN=${0##*/}
+
 case $# in
 	0)
-		printf "${0##*/} quitting, requires a directory argument\n"
+		printf "$PROGN quitting, requires a directory argument\n"
 		exit 2;; 
 	1)
   		if ! [ -d "$1" ]; then
-		printf "${0##*/}: quitting, dirname $1 not found\n"
+		printf "$PROGN quitting, dirname $1 not found\n"
 		exit 2; fi;;
 	*) 
-		printf "${0##*/} quitting, too many arguments, needs just a directory\n" 
+		printf "$PROGN quitting, too many arguments, needs just a directory\n" 
 		exit 2;;
 esac
 
 binkeygen 2048 > testkey.bin
-printf "${0##*/} generated testkey.bin\n"
+printf "$PROGN generated testkey.bin\n"
 
 ecrypt testkey.bin $1
-dcrypt testkey.bin ./${1##*/}-ecr
+dcrypt testkey.bin ./${1##*/}_ecr
 
-printf "${0##*/} found these differences:\n"
-for file in $1/*; do
-    [ -f "$file" ] || continue
-    let count+=1
- 	 diff $file ./${1##*/}-ecr-org/${file##*/} 
+printf "$PROGN found these differences:\n"
+for FILE in $1/*; do
+    [ -f "$FILE" ] || continue
+    let COUNT+=1
+ 	diff $FILE ./${1##*/}_ecr_org/${FILE##*/} 
 done
-printf "${0##*/} tested $count files\n"
+printf "$PROGN tested $COUNT files\n"
diff --git a/ecrypt b/ecrypt
--- a/ecrypt
+++ b/ecrypt
@@ -4,28 +4,31 @@
 # expects also a keyfile argument, e.g. key.bin (to be kept secure)
 # note that 'keygen' can generate a suitable keyfile of any given length 
 
+PROGN=${0##*/}
+
 case $# in
 	0|1)
-		printf "${0##*/} quitting, requires keyfile and dirname arguments\n"
+		printf "$PROGN quitting, requires keyfile and dirname arguments\n"
 		exit 2;; 
 	2)
       if ! [ -f "$1" ]; then
-		printf "${0##*/}: quitting, keyfile $1 not found\n"
+		printf "$PROGN quitting, keyfile $1 not found\n"
 		printf "note that 'keygen' can generate a keyfile of the right length\n"
 		exit 2; fi
 		if ! [ -d "$2" ]; then
-		printf "${0##*/}: quitting, dirname $2 not found\n"
+		printf "$PROGN quitting, dirname $2 not found\n"
 		exit 2; fi;;
 	*) 
-		printf "${0##*/} quitting, too many arguments, needs keyfile and directory\n" 
+		printf "$PROGN quitting, too many arguments, needs keyfile and directory\n" 
 		exit 2;;
 esac
 # output directory for encrypted versions
-OD=${2##*/}-ecr 
+OD=${2##*/}_ecr
 if ! [ -d "$OD" ]; then mkdir $OD; fi
-for file in $2/*; do
-    [ -f "$file" ] || continue
-    let count+=1
-    lzma -z -c $file | symcrypt $1 > $OD/${file##*/}
+
+for FILE in $2/*; do
+    [ -f "$FILE" ] || continue
+    let COUNT+=1
+    lzma -z -c $FILE | symcrypt $1 > $OD/${FILE##*/}
 done
-printf "${0##*/}: encrypted $count files into ./$OD/\n"
+printf "$PROGN encrypted $COUNT files into ./$OD/\n"
diff --git a/hexdcrypt b/hexdcrypt
--- a/hexdcrypt
+++ b/hexdcrypt
@@ -7,6 +7,8 @@
 # to hex encode any file, use: xxd -p file > hexfile
 # to revert back: xxd -p -r hexfile > file
 
+PROGN=${0##*/}
+
 noext() {
 	local c=$( ls -1 *."$1" 2>/dev/null | wc -l )
 if [ $c -eq 0 ]; then return 0; 
@@ -15,22 +17,22 @@ fi
 }
 
 if $( noext scr ); then
-	printf "${0##*/} quitting, no .scr files here in $(pwd)\n" 1>&2
+	printf "$PROGN quitting, no .scr files here in $(pwd)\n" 1>&2
 	exit 2
 fi
 
 if [ $# -ne 1 ]; then
-	printf "${0##*/} needs keyfile argument\n" 1>&2 
+	printf "$PROGN needs keyfile argument\n" 1>&2 
 	exit 2
 fi
 if ! [ -f "$1" ]; then
-	printf "${0##*/}: quitting, keyfile '$1' not found\n" 1>&2
+	printf "$PROGN quitting, keyfile '$1' not found\n" 1>&2
 	exit 2
 fi
 
-for file in ./*.scr; do
-    [ -f "$file" ] || continue
-    let count+=1
-	 symcrypt $1 $file | xxd -p > ${file%.scr}.hex 
+for FILE in ./*.scr; do
+    [ -f "$FILE" ] || continue
+    let COUNT+=1
+	symcrypt $1 $FILE | xxd -p > ${FILE%.scr}.hex 
 done
-printf "${0##*/} decrypted $count files\n" 1>&2
+printf "$PROGN decrypted $COUNT files\n" 1>&2
diff --git a/hexecrypt b/hexecrypt
--- a/hexecrypt
+++ b/hexecrypt
@@ -12,9 +12,11 @@
 # to hex encode any file, use: 'xxd -p file > hexfile'
 # to revert back: 'xxd -p -r hexfile > file'
 
+PROGN=${0##*/}
+
 HEXFILE=$( ls -1 *.hex 2>/dev/null | head -n 1 )
 if [ -z "$HEXFILE" ]; then
-	printf "${0##*/} quitting, no .hex file here in $(pwd)\n" 1>&2
+	printf "$PROGN quitting, no .hex file here in $(pwd)\n" 1>&2
 	exit 2
 fi
 
@@ -23,17 +25,17 @@ case $# in
 		KEYFILE=${HEXFILE%.hex}.key
 		if ! [ -f "$KEYFILE" ]; then 
 			keygen $HEXFILE > $KEYFILE
-			printf "${0##*/} generated keyfile '$KEYFILE' of %d bytes, use it for decrypting\n" \
+			printf "$PROGN generated keyfile '$KEYFILE' of %d bytes, use it for decrypting\n" \
 							$( stat -c%s $KEYFILE ) 1>&2
 		fi;; 
 	1)
 		KEYFILE=$1
         if ! [ -f "$KEYFILE" ]; then
-			printf "${0##*/}: quitting, keyfile '$KEYFILE' not found\n" 1>&2
+			printf "$PROGN quitting, keyfile '$KEYFILE' not found\n" 1>&2
 			exit 2
 		fi;;
 	*) 
-		printf "${0##*/} quitting, too many arguments, takes none or one keyfile argument\n" 1>&2 
+		printf "$PROGN quitting, too many arguments, takes none or one keyfile argument\n" 1>&2 
 		exit 2;;
 esac
 
@@ -42,4 +44,4 @@ for FILE in ./*.hex; do
     let COUNT+=1
     xxd -p -r $FILE | symcrypt $KEYFILE > ${FILE%.hex}.scr
 done
-printf "${0##*/} encrypted $COUNT files\n" 1>&2
+printf "$PROGN encrypted $COUNT files\n" 1>&2
diff --git a/keygen b/keygen
--- a/keygen
+++ b/keygen
@@ -2,19 +2,21 @@
 # given some typical file as an argument, generates an appropriate key for it
 # recognises hexadecimal by extension .hex 
 
+PROGN=${0##*/}
+
 case $# in
 	0)
-		printf 1>&2 "${0##*/} quitting, requires a file argument\n"
+		printf 1>&2 "$PROGN quitting, requires a file argument\n"
 		exit 2;; 
 	1)
   		if ! [ -f "$1" ]; then
-		printf 1>&2 "${0##*/}: quitting, file $1 not found\n"
+		printf 1>&2 "$PROGN quitting, file $1 not found\n"
 		exit 2; fi;;
 	*) 
-		printf 1>&2 "${0##*/} quitting: too many arguments, needs one file\n" 
+		printf 1>&2 "$PROGN quitting: too many arguments, needs one file\n" 
 		exit 2;;
 esac
-# FILE="${1%.*}"
+
 LASTEXT=${1##*.}
 
 if [ "$LASTEXT" == 'hex' ]; then 
diff --git a/superdcrypt b/superdcrypt
--- a/superdcrypt
+++ b/superdcrypt
@@ -7,7 +7,7 @@ PNAME=${0##*/}
 
 case $# in
 	0|1|2)
-		printf "$PNAME quitting, requires keysdir and encrypteddir arguments\n"
+		printf "$PNAME quitting, needs keysdir encrypteddir compressedencrypteddir\n" 
 		exit 2;; 
 	3)
       if ! [ -d "$1" ]; then
@@ -15,30 +15,31 @@ case $# in
 		exit 2; fi
 		if ! [ -d "$2" ]; then
 		printf "$PNAME quitting, encrypted directory $2 not found\n"
-		exit 2; fi;;
+		exit 2; fi
 		if ! [ -d "$3" ]; then
-		printf "$PNAME quitting, compressed encrypted files directory $3 not found\n"
+		printf "$PNAME quitting, compressed encrypted directory $3 not found\n"
 		exit 2; fi;;
 	*) 
-		printf "$PNAME quitting, needs keysydir encrypteddir compressedencrypteddir\n" 
+		printf "$PNAME quitting, needs keysdir encrypteddir compressedencrypteddir\n" 
 		exit 2;;
 esac
 
-# output directory
-OD=${2##*/}-org 
+# make output directory _org
+OD=${2##*/}_org 
 if ! [ -d "$OD" ]; then mkdir $OD; fi
 
+# loop through the keys
 for FILE in $1/*; do
     [ -f "$FILE" ] || continue
     let COUNT+=1
 	FILEND=${FILE##*/}
 	if [ -f $2/$FILEND ]; then
-		symcrypt $1/$FILE $2/$FILE > $OD/$FILEND
+		symcrypt $FILE $2/$FILEND > $OD/$FILEND
 	else if [ -f $3/$FILEND ]; then
-		symcrypt $1/$FILE $3/$FILE | lzma -d -c > $OD/$FILEND
+		symcrypt $FILE $3/$FILEND | lzma -d -c > $OD/$FILEND
 	else 
-		printf "$PNAME quitting, failed to find file $FILEND\n" 
+		printf "$PNAME quitting, failed to find encrypted file $FILEND\n" 
 		exit 2;;
 	fi; fi
 done
-printf "$PNAME decrypted $count files into ./$OD/\n"
+printf "$PNAME decrypted $COUNT files into ./$OD/\n"
