Add files via upload

diff --git a/hexdcrypt b/hexdcrypt
--- a/hexdcrypt
+++ b/hexdcrypt
@@ -11,10 +11,17 @@ if [ $# -ne 1 ]; then
 	printf "${0##*/} needs key-file argument\n" 1>&2 
 	exit 2
 fi
+if ! [ -f "$1" ]; then
+	printf "${0##*/}: quitting, keyfile '$1' not found\n"
+	exit 2
+fi
 
 for file in ./*.scr; do
     [ -f "$file" ] || continue
     let count+=1
-	 symcrypt $1 $file | xxd -p > ${file%.scr}.hex 
+	symcrypt $1 $file | xxd -p > ${file%.scr}.hex 
 done
-printf "${0##*/} decrypted  $count files\n" 
+
+if [ -z "$count" ]; then printf "${0##*/}: quitting, no .scr files found in $(pwd)\n"
+else printf "${0##*/} decrypted  $count files\n"
+fi
diff --git a/hexecrypt b/hexecrypt
--- a/hexecrypt
+++ b/hexecrypt
@@ -18,9 +18,12 @@ case $# in
 		fi;; 
 	1)
 		keyfile=$1
-        [ -f "$keyfile" ] || printf "${0##*/}: quitting, keyfile '$keyfile' not found\n"; exit 2;;
+        if ! [ -f "$keyfile" ]; then
+			printf "${0##*/}: quitting, keyfile '$keyfile' not found\n"
+			exit 2
+		fi;;
 	*) 
-		printf "$0: takes none or one keyfile argument\n" 1>&2 
+		printf "$0: quitting, too many arguments, takes none or one keyfile argument\n" 1>&2 
 		exit 2;;
 esac
 
