new compression encoding

diff --git a/impcrypt b/impcrypt
--- a/impcrypt
+++ b/impcrypt
@@ -5,72 +5,122 @@
 
 PROGN=${0##*/}
 
-# processfile will decompress and decrypt one file
+# importfile will decompress and decrypt one file
 # it expects two arguments: INFILE OUTFILE
-# and it reads from fd 3 which is an open for reading KEYFILE
-function processfile {
+# and it reads from fd 3 which is an opened for reading KEYFILE
+function importfile {
 
 	local INFILE=$1 
 	local OUTFILE=$2
 	local FSIZE=`stat -c%s $INFILE`
 	local CH=`head -c 1 <&3` # read the compression encoding char
-	case "$CH" in
+	head -c $FSIZE <&3 | symcrypt $INFILE | case "$CH" in
 	# u (uncomressed) can be for a listed extension, or because all compressions have failed
-	u ) head -c $FSIZE <&3 | symcrypt $INFILE > $OUTFILE; return;;
-	h ) head -c $FSIZE <&3 | symcrypt $INFILE | hexify > $OUTFILE; return;;
-	b ) head -c $FSIZE <&3 | symcrypt $INFILE | base64 -w 0 > $OUTFILE; return;;
-	i ) head -c $FSIZE <&3 | symcrypt $INFILE | lzma -d > $OUTFILE; return;;
-	j ) head -c $FSIZE <&3 | symcrypt $INFILE | lzma -d | hexify > $OUTFILE; return;;
-	k ) head -c $FSIZE <&3 | symcrypt $INFILE | lzma -d | base64 -w 0 > $OUTFILE; return;;
-	l ) head -c $FSIZE <&3 | symcrypt $INFILE | zstd -d -c > $OUTFILE; return;;
-	m ) head -c $FSIZE <&3 | symcrypt $INFILE | zstd -d -c | hexify > $OUTFILE; return;;
-	n ) head -c $FSIZE <&3 | symcrypt $INFILE | zstd -d -c | base64 -w 0 > $OUTFILE; return;;
-	* ) printf "$PROGN processfile: unrecognised ch\n"; exit 2;;
+	u )  > $OUTFILE; return;;
+	h ) hexify > $OUTFILE; return;;
+	b ) base64 -w 0 > $OUTFILE; return;;
+	i ) lzma -d > $OUTFILE; return;;
+	j ) lzma -d | hexify > $OUTFILE; return;;
+	k ) lzma -d | base64 -w 0 > $OUTFILE; return;;
+	l ) zstd -d -c > $OUTFILE; return;;
+	m ) zstd -d -c | hexify > $OUTFILE; return;;
+	n ) zstd -d -c | base64 -w 0 > $OUTFILE; return;;
+	* ) printf "$PROGN importfile: unrecognised ch\n"; exit 2;;
 	esac
 }
 
-# function to process a whole directory
-# takes three arguments: INDIR KEYDIR OUTDIR
-function processdir {
+# processfile will decompress and decrypt one file
+# it expects three arguments: INDIR KEYDIR OUTDIR
+function processfile {
+
+	local INFILE=$1 
+	local KEYFILE=$2
+	local OUTFILE=$3
+	# the last keyfile extension encodes the compression type in dirs
+	local CH=${KEYFILE##*.}
+	cat $INFILE | symcrypt $KEYFILE | case "$CH" in
+	# u (uncomressed) can be for a listed extension, or because all compressions have failed
+	u ) > $OUTFILE; return;;
+	h ) hexify > $OUTFILE; return;;
+	b ) base64 -w 0 > $OUTFILE; return;;
+	i ) lzma -d > $OUTFILE; return;;
+	j ) lzma -d | hexify > $OUTFILE; return;;
+	k ) lzma -d | base64 -w 0 > $OUTFILE; return;;
+	l ) zstd -d -c > $OUTFILE; return;;
+	m ) zstd -d -c | hexify > $OUTFILE; return;;
+	n ) zstd -d -c | base64 -w 0 > $OUTFILE; return;;
+	* ) printf "$PROGN importfile: unrecognised ch\n"; exit 2;;
+	esac 
+}
+
+# function to import a whole directory
+# takes two arguments: INDIR OUTDIR
+function importdir {
 
 	# create the ouput directory 
 	mkdir $2 || {
-		printf "$PROGN processdir: failed to create output directory '$2'!\n" >&2
+		printf "$PROGN importdir: failed to create output directory '$2'!\n" >&2
 		exit 2
 	}
 	local ITEMS=$(ls -AL $1)
 	# iterate through the listing
 	for ITEM in $ITEMS; do
 		local IND=$1/$ITEM
+		local OUTD=$2/$ITEM
    		if [ -d "$IND" ]; then  # recursively process existing subdirectory?
-			if [ -n "$RECURSE" ]; then  # just push ITEM onto paths, no changing of directories
-				processdir $IND $2/$ITEM
-			fi
-			continue # either processed or ignored this subdir now
+			if [ -n "$RECURSE" ]; then importdir $IND $OUTD; fi
+			continue # done with this subdir
 		fi
    		[ -f "$IND" ] || continue # only process genuine file now
-   		processfile $IND $2/$ITEM 
+   		importfile $IND $OUTD 
+	done
+} 
+
+# function to process a whole directory
+# takes three arguments: INDIR KEYDIR OUTDIR
+function processdir {
+
+	# create the ouput directory
+	mkdir $3
+	[ "$?" -ne 0 ] && {
+		printf "$PROGN processdir: failed to create output directory $3!\n" >&2
+		exit 2
+	}
+	local KEYS=$(ls -AL $2)
+	# iterate through the listing
+	for KEY in $KEYS; do
+		local KD=$2/$KEY
+   		if [ -d "$KD" ]; then  # recursively process existing subdirectory?
+			if [ -n "$RECURSE" ]; then processdir $1/$KEY $KD $3/$KEY & fi
+			continue # either processed or ignored this subdir now
+		fi
+   		[ -f "$KD" ] || continue # only process genuine file now 
+		ROOTN=${KEY%.*} # remove keyfile's encoding extension
+   		processfile $1/$ROOTN $KD $3/$ROOTN &
 	done
 } # end of processdir
 
-function usage { printf "Usage: $PROGN [-h][-q][-r][-v] indir keyfile outdir\n" >&2; }
+function usage { printf "Usage: $PROGN -[h][q][r][v] indir keyfile outdir\n" >&2; }
+function helpmsg {
+	usage
+	printf "\t%s\n" \
+		'-h | --help : print this text' \
+		'-q | --quiet : turn off the final summary' \
+		'-r | --recurse : process also subdirectories' \
+		'-v | --verbose : detailed reporting' >&2
+	exit 1
+}
 
 # Main starts here
 # get options, including long options, extracted as arg to the last option '-'
-while getopts hqrv-: OPT; do
+while getopts dhqrv-: OPT; do
  if [ "$OPT" = "-" ]; then   # long option: reset OPT and OPTARG
     OPT="${OPTARG%%=*}"      # extract long option name
     OPTARG="${OPTARG#$OPT}"  # extract long option argument (here empty)
     OPTARG="${OPTARG#=}"     # remove any assignments `=` from long options
  fi
  case "$OPT" in
-    h | help ) usage; printf "\t%s\n" \
-	'-h | --help : print this text' \
-	'-q | --quiet : turn off the final summary' \
-	'-r | --recurse : process also subdirectories' \
-	'-v | --verbose : detailed reporting' 	
-	exit 1;;
-	# record all presented options
+    h | help ) helpmsg;;
 	q | quiet ) QUIET=0;;
 	r | recurse ) RECURSE=0;;
 	v | verbose ) VERBOSE=0;;  
@@ -80,21 +130,6 @@ while getopts hqrv-: OPT; do
 done
 shift $((OPTIND-1)) # remove already parsed options and args from $@ list
 
-# Globally validate the input file
-[ -f "$1" ] || { 
-	printf "$PROGN: input file '$1' not found\n" >&2
-	exit 2
-}
-# Globally validate the keyfile
-[ -f "$2" ] || { 
-	printf "$PROGN: key file '$2' not found\n" >&2
-	exit 2
-}
-# Globally open the keyfile
-exec 3<$2 || {
-	printf "$PROGN: key file '$2' failed to open for reading\n" >&2
-	exit 2	
-}
 # Globally validate the output directory
 [ -n "$3" ] || { 
 	printf "$PROGN: outdir arg missing\n" >&2
@@ -102,6 +137,17 @@ exec 3<$2 || {
 }
 [ -e "$3" ] && { 
 	printf "$PROGN: output directory '$3' already exists!\n" >&2
+	exit 2
+}
+
+# Globally validate the input file/dir
+[ -e "$1" ] || { 
+	printf "$PROGN: input '$1' not found\n" >&2
+	exit 2
+}
+# Globally validate the keyfile/dir
+[ -e "$2" ] || { 
+	printf "$PROGN: keys '$2' not found\n" >&2
 	exit 2
 }
 
@@ -119,21 +165,35 @@ if [ -z $( which hexify ) ]; then
 	printf "$PROGN warning, hexify is not installed, will not unpack .hex files\n" >&2
 fi
 
-tar -xpJf $1 $1dir # $1dir is temporary encrypted dir unpacked
-printf "$PROGN: decrypting and decompressing\n" 
-processdir $1dir $3
-rm -rf $1dir
+if [ -f "$1" ] && [ -f "$2" ]; then
+	# Globally open the keyfile
+	exec 3<$2 || {
+		printf "$PROGN: key file '$2' failed to open for reading\n" >&2
+		exit 2	
+	}
+	tar -xpJf $1 $1dir # $1dir is temporary encrypted dir, untarred
+	printf "$PROGN: decrypting and decompressing archives files\n" 
+	importdir $1dir $3
+	rm -rf $1dir # tidy up temp encrypted dir
+else 
+	if [ -d "$1" ] && [ -d "$2" ]; then 
+		processdir $1 $2 $3
+		printf "$PROGN: decrypting dirs using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
+		wait
+	else
+		printf "$PROGN: inputs '$1' '$2' must be either both directories or both files\n" >&2
+		exit 2
+	fi
+fi
 
 # optional final report
 if ! [ $QUIET ]; then
-	SIZES=( $( du -hbs $3 $1 ) ) # array of size,dir,size,dir
-	# let SIZES[0]-=4096 # subtract the size of the top directory files
-	# let SIZES[2]-=4096 # as they are not actual data
+	SIZES=( `du -hbs $3 $1` ) # array of size,dir,size,dir
 	printf "$PROGN: ${SIZES[3]} ${SIZES[2]} "
 	if [ ${SIZES[0]} = ${SIZES[2]} ]; then printf "(100 %%) => ${SIZES[1]} ${SIZES[0]}\n"; else
 		CR=$(( (5+100000*${SIZES[2]}/${SIZES[0]})/10 )) # calculate percentage rounded to two d.p.	
 		printf "(${CR: 0:2}.${CR: 2:4} %%) => ${SIZES[1]}: ${SIZES[0]}\n"
 	fi
 	# compressed size x 10^5, printed as xx.xx% 
-	printf "$PROGN: decrypted $1 into $3\n" >&2
+	printf "$PROGN: decrypted '$1' into '$3'\n" >&2
 fi
diff --git a/ncrpt b/ncrpt
--- a/ncrpt
+++ b/ncrpt
@@ -6,7 +6,6 @@
 PROGN=${0##*/}
 COMPRESSOR=lzma	# the default compression program
 EXT=lz			# and the extension that goes with it
-BACKSZ=10000 	# size of files to be encrypted in the subshells
 
 # function to compress and encrypt one file
 # takes three arguments: INDIR KEYDIR OUTDIR
@@ -14,48 +13,62 @@ BACKSZ=10000 	# size of files to be encrypted in the subshells
 # creates and cleans up two temporary files in OUTDIR
 function processfile {
 
-	local INFILE=$1 
-	local KEYFILE=$2
+	local INFILE=$1
+	local KEYFILE=$2 
 	local OUTFILE=$3
 	local EX="${1##*.}" # this file's extension
-	EX=${EX,,} # convert to lower case for ease of detecting either
+	local CH='u'
 
-	# if EX passes one of these tests, then avoid all compression 
+	EX=${EX,,} # convert to lower case, to detect both cases
+	# if EX passes any one of these tests, then avoid all compression 
 	[ "$EX" = 'jpg' ] || [ "$EX" = 'jpeg' ] || [ "$EX" = 'mp4' ] || [ "$EX" = 'zip' ] || [ "$EX" = '7z' ] || \
-	[ "$EX" = 'lz' ] || [ "$EX" = 'zst' ] || [ "$EX" = 'gz' ] || [ "$EX" = 'bz2' ] || {
+	[ "$EX" = 'lz' ] || [ "$EX" = 'zst' ] || [ "$EX" = 'gz' ] || [ "$EX" = 'bz2' ] && {
+		keygen $INFILE | tee -a "$KEYFILE.u" | symcrypt $INFILE > $OUTFILE
+		return
+	}
 
-    	[ $HEXTEST ] && {
-   			hexcheck $INFILE $OUTFILE.tmp000 2>/dev/null # ignore failure messages
-   			if [ "$?" -eq 0 ]; then	# status of hexcheck when INFILE is entirely hexadecimal
-				INFILE="$OUTFILE".tmp000 # now this becomes the binary file to further compress
-				KEYFILE="$KEYFILE".hex # append .hex extension for hexadecimal origin
-   			fi
-		}
+    if [ $HEXTEST ] && hexcheck $INFILE $OUTFILE.tmp 2>/dev/null; then 
+		CH='h'
+		INFILE=$OUTFILE.tmp 
+	else if [ $B64TEST ] &&	base64 -d -w 0 $INFILE > $OUTFILE.tmp 2>/dev/null; then 
+		CH='b'
+		INFILE=$OUTFILE.tmp 
+		fi
+	fi
 
-		[ $B64TEST ] && [ "$INFILE" = "$1" ] && { #  still the original input file?
-   			base64 -d -w 0 $INFILE > $OUTFILE.tmp000 2>/dev/null # turns base64 into binary, saving 25%
-   			if [ "$?" -eq 0 ]; then	# status of base64 when INFILE was entirely in base64
-				INFILE="$OUTFILE".tmp000 # now this becomes the binary file to further compress
-				KEYFILE="$KEYFILE".b64 # append .b64 extension for base64 origin
-   			fi 
-		}
-	
-		# regardless whether hexcheck or base64 tests succeeded or not, test general compression	
-		$COMPRESSOR $FLAGS $INFILE > $OUTFILE.tmp001 
-		local CMPS=$( stat -c%s $OUTFILE.tmp001 ) # the size after compression
+	# regardless whether hexcheck or base64 tests succeeded or not, apply general compression test	
+	$COMPRESSOR $FLAGS $INFILE > $OUTFILE.cmp 
+		local CMPS=$( stat -c%s $OUTFILE.cmp ) # the size after compression
 		local ORGS=$( stat -c%s $INFILE )  # and before compression
 		# use compressed version only if it is actually smaller
-		if [ "$CMPS" -lt "$ORGS" ]; then 
-			KEYFILE="$KEYFILE".$EXT # append compression extension to the keyfile to be generated
-			INFILE="$OUTFILE".tmp001  # assign the compressed file name, else stay with previous
-		fi
-	}
-	# generate and write out the key of the same size as the infile
-	keygen $INFILE > $KEYFILE
-	# encrypt with it and write to OUTFILE 
-	symcrypt $INFILE $KEYFILE $OUTFILE 
-	rm $OUTFILE.tmp000 $OUTFILE.tmp001 2> /dev/null  #tidy up if needed
-}
+		[ "$CMPS" -lt "$ORGS" ] && { # successful general compression
+			INFILE=$OUTFILE.cmp # make the final compressed file to be the infile
+			if [ "$COMPRESSOR" = 'lzma' ]; then
+			 case "$CH" in
+			 u ) CH='i';;
+			 h ) CH='j';;
+			 b ) CH='k';;
+			 * ) printf "$PROGN processfile: unrecognised ch\n"
+			 	 exit 2;;
+			 esac
+			else # compressor program is 'zstd'
+			 case "$CH" in
+			 u ) CH='l';;
+			 h ) CH='m';;
+			 b ) CH='n';;
+			 * ) printf "$PROGN processfile: unrecognised ch\n"
+			 	 exit 2;;
+			 esac
+			fi				
+		} # else no general compression gain, keep the original INFILE and codes: u,h,b
+		
+	# generate key of the same size as infile,
+	# encrypt with it and write to OUTFILE.$CH 
+	keygen $INFILE | tee -a "$KEYFILE.$CH" | symcrypt $INFILE > $OUTFILE
+	# clean up
+	if [ -e "$OUTFILE.tmp" ]; then rm $OUTFILE.tmp; fi 
+	if [ -e "$OUTFILE.cmp" ]; then rm $OUTFILE.cmp; fi 
+} # end of processfile
 
 # function to process a whole directory
 # takes three arguments: INDIR KEYDIR OUTDIR
@@ -83,12 +96,8 @@ function processdir {
 		printf "$PROGN quitting, failed to create output directories '$2' '$3'!\n" >&2
 		exit 2
 	}
-
-	# sort files in INDIR by size
-	# stripping the path path prior to using ls was done thus: FILEND=${INFILE##*/} 
+	
 	local ITEMS=$(ls -AL $1)		#$(ls -SAL $1)
-	# prepare to fire off subshells
-	# local BJ=\&
 
 	# iterate through the listing
 	for ITEM in $ITEMS; do
@@ -100,9 +109,7 @@ function processdir {
 			continue # either processed or ignored this subdir now
 		fi
    		[ -f "$IND" ] || continue # only process genuine file now
- 		# turn off subshells when file size falls below BACKSZ
-   		# [ -z "$BJ" ] || [ $( stat -c%s $IND ) -ge $BACKSZ ] || BJ='' 
-   		processfile $IND $2/$ITEM $3/$ITEM & #$BJ 
+   		processfile $IND $2/$ITEM $3/$ITEM &  
 	done
 } # end of processdir
 
@@ -118,12 +125,7 @@ function updatedir {
 		printf "$PROGN updatedir: output dir $3 is invalid\n" >&2
 		exit 2
 	}
-
-	# sort files in INDIR by size
-	# stripping the path path prior to using ls was done thus: FILEND=${INFILE##*/} 
 	local ITEMS=$(ls -AL $1)  # $(ls -SAL $1)
-	# prepare to fire off subshells
-	# local BJ=\&
 	# iterate through the listing checking for newer items
 	for ITEM in $ITEMS; do
 		local ID=$1/$ITEM # append $ITEM to $INDIR path
@@ -134,31 +136,29 @@ function updatedir {
 				[ -d "$OD" ] || { # here matching dir does not exist
 					printf " A: $ID\n" # so add it
 					# just push ITEM onto paths 
-					processdir $ID $2/$ITEM $OD & #$BJ
+					processdir $ID $2/$ITEM $OD &
 					continue
 				}
 				# test the dirs modification times
 				# note that -nt only works for additions/deletions to dirs			
 				if [ $(stat -c%Y $ID) -gt $(stat -c%Y $OD) ]; then 
 					printf " U: $ID\n" # so update it
-					updatedir $ID $2/$ITEM $OD & #$BJ
+					updatedir $ID $2/$ITEM $OD &
 					continue
 				fi
 				continue # up to date dir
 			fi
 			continue # not recursing, ignore this subdir 
 		fi
-   		[ -f "$ID" ] || continue # only process genuine files now
- 		# turn off subshells when file size falls below BACKSZ
-   		# [ -z "$BJ" ] || [ $( stat -c%s $ID ) -ge $BACKSZ ] || BJ='' 
+   		[ -f "$ID" ] || continue # only process genuine files now 
 		[ -e "$OD" ] || { # here $OD file does not exist
 			printf "   a: $ID\n" # so add it
-			processfile $ID $2/$ITEM $OD & #$BJ 
+			processfile $ID $2/$ITEM $OD & 
 			continue
 		}
 		if [ "$ID" -nt "$OD" ]; then  # here the input file is newer 
 			printf "   u: $ID\n" # so update it
-   			processfile $ID $2/$ITEM $OD & #$BJ 
+   			processfile $ID $2/$ITEM $OD & 
 		fi # else just skip it
 	done
 } # end of updatedir
@@ -208,7 +208,7 @@ function cleandir {
 	done
 } # end of cleandir
 
-function usage { printf "Usage: $PROGN [-b][-c][-h][-q][-r][-u][-v][-x][-z] indir keydir outdir\n" >&2; }
+function usage { printf "Usage: $PROGN -[b][c][h][q][r][u][v][x][z] indir keydir outdir\n" >&2; }
 
 function helpmsg {
 	usage
@@ -266,15 +266,15 @@ if [ $VERBOSE ]; then
 fi
 
 if [ $UPDATE ]; then 
-	printf "$PROGN: updating archive $3, using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
+	printf "$PROGN: updating archive '$3', using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
 	updatedir $1 $2 $3
 else
-	printf "$PROGN: compressing and encrypting $1, using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
+	printf "$PROGN: encrypting '$1', using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
 	processdir $1 $2 $3
 fi
 wait # for all sub proccesses to finish
 if [ $CLEAN ]; then 
-	printf "$PROGN: cleaning up archive $3\n" 
+	printf "$PROGN: cleaning up archive '$3'\n" 
 	cleandir $1 $2 $3
 fi
 wait # for all sub proccesses to finish
@@ -282,12 +282,12 @@ wait # for all sub proccesses to finish
 # optional final report
 if ! [ $QUIET ]; then
 	SIZES=( $( du -bs $3 $1 ) ) # array of size,dir,size,dir
-	let "SIZES[0]-=4096"
-	let "SIZES[2]-=4096"	
+	# let "SIZES[0]-=4096"
+	# let "SIZES[2]-=4096"	
 	printf "$PROGN: ${SIZES[3]} ${SIZES[2]} => ${SIZES[1]} ${SIZES[0]} "
 	if [ ${SIZES[0]} = ${SIZES[2]} ]; then printf "(100 %%)\n"; else
 		CR=$(( (5+100000*${SIZES[0]}/${SIZES[2]})/10 )) # calculate percentage rounded to two d.p.	
 		printf "(${CR: 0:2}.${CR: 2:4} %%)\n" # compression ratio printed as xx.xx%
 	fi 
-	printf "$PROGN: keys are in $2\n"
+	printf "$PROGN: keys are in '$2'\n"
 fi
