-u option

diff --git a/ncrpt b/ncrpt
--- a/ncrpt
+++ b/ncrpt
@@ -87,13 +87,13 @@ function processdir {
 
 	# sort files in INDIR by size
 	# stripping the path path prior to using ls was done thus: FILEND=${INFILE##*/} 
-	ITEMS=$(ls -SAL $1)
+	local ITEMS=$(ls -SAL $1)
 	# prepare to fire off subshells
-	BJ=\&
+	local BJ=\&
 
 	# iterate through the listing
 	for ITEM in $ITEMS; do
-		local IND=$1/$ITEM
+		local IND=$1/$ITEM # append $ITEM to $INDIR path
    		if [ -d "$IND" ]; then  # recursively process existing subdirectory?
 			if [ -n "$RECURSE" ]; then  # just push ITEM onto paths, no changing of directories
 				processdir $IND $2/$ITEM $3/$ITEM &
@@ -107,32 +107,116 @@ function processdir {
 	done
 } # end of processdir
 
+# function to update a whole directory
+# takes three arguments: INDIR KEYDIR OUTDIR
+function updatedir {
+
+	[ -d "$1" ] || {
+		printf "$PROGN quitting update, input dir $1 is invalid\n" >&2
+		exit 2
+	}
+	[ -d "$2" ] || {
+		printf "$PROGN quitting update, key dir $2 is invalid\n" >&2
+		exit 2
+	}
+	[ -d "$3" ] || {
+		printf "$PROGN quitting update, output dir $3 is invalid\n" >&2
+		exit 2
+	}
+
+	# sort files in INDIR by size
+	# stripping the path path prior to using ls was done thus: FILEND=${INFILE##*/} 
+	local ITEMS=$(ls -SAL $1)
+	# prepare to fire off subshells
+	local BJ=\&
+	# iterate through the listing checking for newer items
+	for ITEM in $ITEMS; do
+		local IND=$1/$ITEM # append $ITEM to $INDIR path
+		local OD=$3/$ITEM # and corresponding $outdir path
+
+   		if [ -d "$IND" ]; then  # recursively process existing subdirectory?
+			if [ -n "$RECURSE" ]; then  # just push ITEM onto paths
+				[ -d "$OD" ] || { # here matching dir does not exist
+					printf "A: $IND\n" # so add it
+					processdir $IND $2/$ITEM $3/$ITEM &
+					continue
+				}			
+				[ "$IND" -nt "$OD" ] && { # here input dir is newer
+					printf "U: $IND\n" # so update it
+					udpatedir $IND $2/$ITEM $3/$ITEM &
+				}
+				cleandir $IND $2/$ITEM $OD # check deletions
+			fi
+			continue # either processed or ignored this subdir now
+		fi
+   		[ -f "$IND" ] || continue # only process genuine files now
+ 		# turn off subshells when file size falls below BACKSZ
+   		[ -z "$BJ" ] || [ $( stat -c%s $IND ) -ge $BACKSZ ] || BJ='' 
+		[ "$IND" -nt "$OD" ] && { # here input file is newer 
+			printf "R: $IND\n" # so replace it
+   			processfile $ITEM $1 $2 $3 $BJ 
+		} # otherwise just skip it
+	done
+	 # rm any dirs or files that are no longer in indir
+	 # from outdir and keydir
+	cleandir $1 $2 $3
+} # end of updatedir
+
+# cleans up any dirs and files from keydir, outdir 
+# that are no longer present in indir
+function cleandir {
+
+	local ITEMS=$(ls -AL $3) # iterate through OUTDIR in any order
+	for ITEM in $ITEMS; do
+		local IND=$1/$ITEM # append $ITEM to $INDIR path
+		local OD=$3/$ITEM # and corresponding $outdir path
+	  	if [ -d "$OD" ]; then # it is a directory
+			[ -d "$IND" ] || { # no longer in IND
+				printf "D: $2/$ITEM $OD\n" # so delete them 
+				rm -rf $2/$ITEM $OD & # from KEYIR OUTDIR
+			}
+			continue
+		fi 
+		if [ -f "$OD" ]; then # it is a file
+			[ -f "$IND" ] || { # no longer in IND				
+				printf "D: $2/$ITEM.* $OD\n" # so delete them 
+				rm "$2/$ITEM.*" "$OD"
+			}
+		fi 
+	done	
+}	
+
 function usage { printf "Usage: $PROGN [-h][-b][-x][-q][-r][-v][-z] indir keydir outdir\n" >&2; }
 
+function helpmsg {
+	usage
+	printf "\t%s\n" \
+		'-b | --b64 : test for base64 encoded files' \
+		'-h | --help : print this text' \
+		'-q | --quiet : turn off the final summary' \
+		'-r | --recurse : process also subdirectories' \
+		'-u | --update : update' \
+		'-v | --verbose : detailed reporting' \
+		'-x | --hex : test for hexadecimal files' \
+		'-z | --zstd : use zstd compression instead of lzma' >&2
+	exit 1
+}
 # Main starts here
 # get options, including long options, extracted as arg to the last option '-'
-while getopts hbxqrvz-: OPT; do
+while getopts hbxqruvz-: OPT; do
  if [ "$OPT" = "-" ]; then   # long option: reset OPT and OPTARG
     OPT="${OPTARG%%=*}"      # extract long option name
     OPTARG="${OPTARG#$OPT}"  # extract long option argument (here empty)
     OPTARG="${OPTARG#=}"     # remove any assignments `=` from long options
  fi
  case "$OPT" in
-    h | help ) usage; printf "\t%s\n" \
-		'-b | --b64 : test for base64 encoded files' \
-		'-h | --help : print this text' \
-		'-q | --quiet : turn off the final summary' \
-		'-r | --recurse : process also subdirectories' \
-		'-v | --verbose : detailed reporting' \
-		'-x | --hex : test for hexadecimal files' \
-		'-z | --zstd : use zstd compression instead of lzma' 
-		exit 1;;
-	# record all presented options
+    h | help ) helpmsg;;
 	b | b64 ) B64TEST=0;; 
 	x | hex ) HEXTEST=0;;
 	q | quiet ) QUIET=0;;
 	v | verbose ) VERBOSE=0;; 
 	r | recurse ) RECURSE=0;;
+	u | update ) UPDATE=0;;
   	z | zstd ) COMPRESSOR=zstd; EXT=zst;; #alternative compressor and its extension
     ??* ) printf "$PROGN quitting, invalid long option: $OPT\n" >&2; usage; exit 2;;  
 	*) exit 2;;  # invalid short option (error will be reported via getopts)
@@ -145,17 +229,24 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 	printf "$PROGN quitting, input directory $1 not found\n" >&2
 	exit 2
 }
+
 # Globally validate the compressor. It has been set either to lzma or zstd
 [ -z $( which "$COMPRESSOR" ) ] && { 
 	printf "$PROGN quitting, compressor utility $COMPRESSOR not found\n" >&2
 	exit 2
 }
+
 FLAGS='-c -z -q' # the default lags to the compressor
 if [ $VERBOSE ]; then 
 	if [ "$COMPRESSOR" = 'lzma' ]; then FLAGS='-c -z -v';	else FLAGS='-c'; fi
 fi
+
 printf "$PROGN encrypting and compressing, using %d cores\n" $( grep -c ^processor /proc/cpuinfo )
-processdir $1 $2 $3
+if [ $UPDATE ]; then 
+	updatedir $1 $2 $3
+else
+	processdir $1 $2 $3
+fi
 wait # for all sub proccesses to finish
 
 # optional final report
