more quoting

diff --git a/unpack b/unpack
--- a/unpack
+++ b/unpack
@@ -30,7 +30,7 @@ function importdir {
         # or because all compression attempts have failed to gain
         # read from infile (fd 3) and write the file data as is
 	    [ "$CH" = 'u' ] && {
-            head -c $FSIZE <&3 > $NAME 
+            head -c "$FSIZE" <&3 > "$NAME" 
 		    continue
 	    }
         # apply code specified decompression to a compressed file
@@ -114,33 +114,33 @@ if [ -z $( which hexify ) ]; then
 	printf "$PROGN warning, hexify is not installed, will not unpack .hex files\n" >&2
 fi
 
-INDEXSIZE=`stat -c%s $1` # get size of indexfile
+INDEXSIZE=`stat -c%s "$1"` # get size of indexfile
 INFILE=_infile.tmp # temporary file for decrypted files data input
 # decrypt infile with tail of keyfile
-tail -c +$(( "$INDEXSIZE" + 1 )) $3 | symcrypt $2 > $INFILE
+tail -c +$(( "$INDEXSIZE" + 1 )) "$3" | symcrypt "$2" > "$INFILE"
 # Open the infile as file descriptor 3
-exec 3<$INFILE || {
+exec 3<"$INFILE" || {
 	printf "$PROGN: infile file '$INFILE' failed to open for reading\n" >&2
 	exit 2	
 }
 # decrypt indexfile with head of keyfile, lzma uncompress, and pipe to importdir
-head -c $INDEXSIZE $3 | symcrypt $1 | lzma -d | { 
+head -c $INDEXSIZE "$3" | symcrypt "$1" | lzma -d | { 
     read -r -d ',' DIRNAME
     [ -e "$DIRNAME" ] && { 
 	    printf "$PROGN: output directory '$DIRNAME' already exists!\n" >&2
 	    exit 2
     }
-    mkdir $DIRNAME || {
+    mkdir "$DIRNAME" || {
 	printf "$PROGN: failed to create output directory '$DIRNAME'!\n" >&2
 	exit 2
     }
     printf "$PROGN: restoring directory '$DIRNAME'\n"
-    importdir $DIRNAME
-    rm $INFILE # clean up
+    importdir "$DIRNAME"
+    rm "$INFILE" # clean up
 
     # optional final report
     if ! [ $QUIET ]; then
-	    SIZES=( `du -hbs $DIRNAME $3` ) # array of size,dir,size,file
+	    SIZES=( `du -hbs "$DIRNAME" "$3"` ) # array of size,dir,size,file
 	    printf "$PROGN: ${SIZES[3]} ${SIZES[2]} %s"
 	    if [ ${SIZES[0]} = ${SIZES[2]} ]; then 
             printf "(100 %%) => ${SIZES[1]} ${SIZES[0]}\n"
